version: "3.2"

services:
  website:
    build:
      context: .
      dockerfile: website.dockerfile
    links:
      - mqtt
    expose:
      - "80"
    restart: always

  proxy:
    image: abiosoft/caddy
    links:
      - website
    external_links:
      - app:discourse
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - ./.caddy:/root/.caddy
    restart: always

  ministerin:
    build:
      context: .
      dockerfile: ministerIN.dockerfile
    ports:
      - "7777:7777"
    depends_on:
      - mqtt
    restart: always

  mqtt:
    build:
      context: .
      dockerfile: mqtt.dockerfile
    volumes:
      - ./credentials/mqtt:/var/local/mosquitto:ro
    ports:
      - "8883:8883"
    restart: always
