version: "3.2"

services:
  website:
    build:
      context: .
      dockerfile: website.dockerfile
    links:
      - mqtt
    expose:
      - "80"
      - "443"
    volumes:
      - /etc/letsencrypt/live/www.lambdaspace.gr:/etc/letsencrypt/live/www.lambdaspace.gr:ro
      - /etc/letsencrypt/archive/www.lambdaspace.gr:/etc/letsencrypt/archive/www.lambdaspace.gr:ro
    restart: always

  proxy:
    image: haproxy:1.7-alpine
    links:
      - website
    external_links:
      - app:discourse
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: always

  ministerin:
    build:
      context: .
      dockerfile: ministerIN.dockerfile
    ports:
      - "7777:7777"
    depends_on:
      - mqtt
    restart: always

  mqtt:
    build:
      context: .
      dockerfile: mqtt.dockerfile
    volumes:
      - ./credentials/mqtt:/var/local/mosquitto:ro
    ports:
      - "8883:8883"
    restart: always
